from pathlib import Path
import json,html
root=Path(__file__).resolve().parents[1]
d=root/'design/directions'
record=json.loads((root.parent/'querypilot/backend/evaluation_results/day6_full_results.json').read_text(encoding='utf-8'))
trace=next(r for r in record['results'] if r['id']=='hard_001')
safe={k:trace[k] for k in ['id','question','sql','success','attempts','first_attempt_success','schema_tables_used','correction_applied']}
safe.update(commit='1b7547649f9d883111c3020b46efde9a6bbe7e6c',recordedAt=record['timestamp'],source='backend/evaluation_results/day6_full_results.json')
(d/'assets/querypilot-trace-v1.json').write_text(json.dumps(safe,indent=2),encoding='utf-8')
def building(x,y,label,kind):
    windows=''.join(f'<path d="M{xx} {yy}v15m9-10v15"/>' for xx in [-51,-28,-5] for yy in [-30,-65,-100])
    if kind==0:
        art=f'<path d="M-75 0V-115L0-150 70-115V0L0 35Z" fill="#335578"/><path d="M0 35V-80L70-115V0Z" fill="#1f385a"/><path d="M-75-115L0-150 70-115 0-80Z" fill="#90a4a5"/><g stroke="#e1d5ad" stroke-width="3">{windows}</g><path d="M20 11v-43q18-30 28-14v44" fill="#e5c994"/>'
    elif kind==1:
        art='<path d="M-70 0V-85L0-120 75-85V0L0 35Z" fill="#466784"/><path d="M0 35V-50L75-85V0Z" fill="#264763"/><path d="M-70-85L0-120 75-85 0-50Z" fill="#acb3a1"/><path d="M-30-104V-182L0-201 30-184V-103L0-88Z" fill="#6d8b99"/><path d="M0-88V-166L30-184V-103Z" fill="#315779"/><path d="M-30-182L0-201 30-184 0-166Z" fill="#e7cda0"/><path d="M0-201V-228L35-210 0-210" fill="#c7563b" stroke="#294663" stroke-width="2"/><path d="M-55-62v35m18-26v35m18-26v35M20-28V7m20-45v35m20-45v35" stroke="#e3d5af" stroke-width="5"/>'
    elif kind==2:
        art='<path d="M-80 0V-55L0-95 80-55V0L0 40Z" fill="#728b97"/><path d="M0 40V-15L80-55V0Z" fill="#405f78"/><path d="M-80-55L0-95 80-55 0-15Z" fill="#c9c6a8"/><path d="M-55-57V-90L0-117 55-90V-57L0-30Z" fill="#89a0a6"/><path d="M-55-90L0-117 55-90 0-63Z" fill="#e0d3ad"/><path d="M-65-30v23m20-13v23m20-13v23M18 1v23m20-33v23m20-33v23" stroke="#e9d4a7" stroke-width="4"/>'
    else:
        art='<path d="M-75 0V-60L0-98 75-60V0L0 38Z" fill="#365877"/><path d="M0 38V-23L75-60V0Z" fill="#244561"/><path d="M-75-60L0-98 75-60 0-23Z" fill="#a9b4a7"/><path d="M-65-65L0-136 65-65 0-35Z" fill="#c48562"/><path d="M0-136L65-65 0-35Z" fill="#9d5d43"/><path d="M-56-31v18m18-9v18m18-9v18M20-10v25m22-37v25" stroke="#e2d2ad" stroke-width="4"/>'
    return f'<g class="district" data-district="{label}" transform="translate({x},{y})"><ellipse cy="22" rx="96" ry="32" fill="#263d5720"/><g class="district-rise">{art}</g><g class="map-label" transform="translate(0,70)"><rect x="-75" y="-17" width="150" height="30" rx="2" fill="#f7eac7" stroke="#24445f"/><text text-anchor="middle" y="3">{label}</text></g></g>'
buildings=''.join(building(x,y,n,k) for k,(x,y,n) in enumerate([(260,300,'customers'),(620,255,'orders'),(790,500,'order_items'),(380,560,'products')]))
marks=''.join(f'<path d="M{x} 60v8M{x} 740v-8"/>' for x in range(100,1150,25))
tiles=''.join(f'<rect class="ledger-tile" data-tile="{i}" x="{115+(i%14)*70}" y="{270+(i//14)*63}" width="47" height="42" rx="2"/>' for i in range(70))
svg=f'''<svg class="atlas-drawing" viewBox="0 0 1200 800" role="img" aria-label="An editorial atlas: four schema districts and a route that can fail, be corrected, and reach a read-only gate."><defs><mask id="route-break"><rect width="1200" height="800" fill="white"/><rect class="broken-gap" x="762" y="292" width="85" height="85" fill="black" opacity="0"/></mask><pattern id="hatch" width="6" height="6" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><path d="M0 0v6" stroke="#c45a3b" stroke-width="2"/></pattern></defs><g class="survey" fill="none" stroke="#3a59704d" stroke-width="1">{marks}<rect x="65" y="65" width="1070" height="670"/><path d="M65 400H1135M600 65V735" stroke-dasharray="3 9"/><circle cx="600" cy="400" r="245" stroke-dasharray="2 12"/><path d="M90 695h100m-90-10v20m80-20v20"/></g><g class="routes" fill="none"><path class="route-ghost" d="M115 620L260 300 620 255 1005 420"/><path id="proposal-route" mask="url(#route-break)" d="M115 620Q170 400 260 300L620 255 1005 420"/><path id="corrected-route" d="M115 620Q170 400 260 300L620 255Q720 250 685 360L560 420Q510 455 560 485L810 625Q910 650 1005 420"/></g><g class="city">{buildings}<g class="database-gate" transform="translate(1005,420)"><ellipse cy="27" rx="65" ry="24" fill="#20375524"/><path d="M-52 0V-95L0-125 52-95V0L25 15V-65Q0-100-25-65V15Z" fill="#244b6b" stroke="#142f4c" stroke-width="2"/><path d="M-52-95L0-125 52-95 0-67Z" fill="#a7b7ad"/><path class="gate-bar" d="M-43-40H43" stroke="#c4553c" stroke-width="12"/><text y="62" text-anchor="middle" fill="#233c55">READ ONLY</text></g></g><g class="fracture" transform="translate(800,333)" stroke="#bd492f" fill="none" stroke-width="5"><path d="M-20-30L10-9-9 13 22 35"/><path d="M-43-28L-60-40M43 25L60 38M8-43L15-66" stroke-width="2"/></g><g class="traveller"><path d="M-18-14L26 0-18 14-8 0Z" fill="#c84c31" stroke="#7f3627" stroke-width="2"/><path d="M-8 0H26" stroke="#ffe2b0" stroke-width="2"/></g><g class="ledger-grid">{tiles}<text x="115" y="220" class="ledger-title">70 CORE JOURNEYS</text><text x="115" y="640" class="ledger-label">EXECUTION SUCCESS · NOT SEMANTIC ACCURACY</text></g><g class="arrival-stamp" transform="translate(600,400) rotate(-8)"><rect x="-270" y="-80" width="540" height="160" fill="#f4e8c9" stroke="#244e63" stroke-width="7"/><rect x="-258" y="-67" width="516" height="134" fill="none" stroke="#244e63"/><text text-anchor="middle" y="12">EXECUTED</text><text class="stamp-sub" text-anchor="middle" y="51">MEANING: STILL TO BE CHECKED</text></g></svg>'''
sql=html.escape(trace['sql'])
chapters=[('fold','01 / THE CARTOGRAPHER’S FOLD','h1','Every question<br>needs a way<br><em>through.</em>','A small atlas of mistakes, corrections,<br>and the limits of arriving.','QueryPilot turns natural language into inspectable, read-only SQL. Unfold its world with your scroll.','<a class="begin-link" href="#question">Unfold the atlas <span>↓</span></a>'),
('question','02 / A QUESTION SETS OUT','h2','Start with<br>a question.','One actual question. One recorded journey.','The map is a metaphor. The question and final SQL come from the committed <code>hard_001</code> evaluation record.',f'<blockquote>{html.escape(trace["question"])}<cite>DAY 6 · HARD_001</cite></blockquote>'),
('schema','03 / FIND THE TERRITORY','h2','You can’t cross<br>an unknown city.','First, retrieve the relevant schema.','The recorded context contains orders, customers, order_items and products. Their architecture and positions are invented for this atlas; they are not a database plan.','<label class="turn-control" for="atlas-angle">Turn the atlas <input id="atlas-angle" type="range" min="-25" max="25" value="0"><span>Move the map. Keep the evidence.</span></label><div class="district-controls" role="group" aria-label="Inspect retrieved tables">'+''.join(f'<button type="button" data-table="{t}" aria-pressed="false">{t}</button>' for t in trace['schema_tables_used'])+'</div><p class="table-result" aria-live="polite">Four table names recorded in the retrieved context.</p>'),
('proposal','04 / A POSSIBLE CROSSING','h2','A route is<br>only a proposal.','The generator writes SQL. The checks get a say.','Static criticism, safety checks and database execution can reject a statement that looks convincing. A drawn line does not make a bridge.','<div class="margin-record"><span>SCHEMA → GENERATION</span><strong>Proposal, not permission.</strong></div>'),
('fracture','05 / THE FIRST ATTEMPT','h2','Almost<br>isn’t across.','The first attempt did not succeed.','The Day 6 record preserves that result and the final SQL. It does not preserve the SQL or failure reason for every intermediate attempt. The broken bridge illustrates failure; it does not diagnose it.','<div class="failed-seal">FIRST ATTEMPT<br><strong>UNSUCCESSFUL</strong></div>'),
('redraw','06 / BOUNDED CORRECTION','h2','Draw again.<br>Know when to stop.','This recorded query took three attempts.','Structured failure feedback can return to the correction path. The attempt budget is bounded; cosmetic rewrites do not earn endless retries.','<div class="attempt-controls" role="group" aria-label="Inspect the recorded attempt boundary"><button type="button" data-attempt="1" aria-pressed="false">First attempt</button><button type="button" data-attempt="2" aria-pressed="false">Between attempts</button><button type="button" data-attempt="3" aria-pressed="true">Final · attempt 3</button></div><p class="attempt-result" aria-live="polite">Final attempt: execution succeeded. Three attempts recorded.</p><details class="sql-record"><summary>Unfold the exact final SQL</summary><p>Committed Day 6 output · no SQL is executed here.</p><pre tabindex="0"><code>'+sql+'</code></pre></details>'),
('gate','07 / THE READ-ONLY GATE','h2','A crossing isn’t<br>permission.','Correction must not erase the guardrails.','Safety is checked again after correction. Database acceptance alone cannot authorize destructive or sensitive intent. Try the boundary in this illustration.','<div class="guard-controls" role="group" aria-label="Illustrate read-only boundary"><button type="button" data-intent="read" aria-pressed="true">Read-only intent</button><button type="button" data-intent="write" aria-pressed="false">Destructive intent</button></div><p class="guard-result" aria-live="polite">Illustration: read-only intent may proceed after the remaining checks. No database request is made.</p>'),
('ledger','08 / THE HONEST LEDGER','h2','Four more<br>made it through.','63 → 67 execution successes. Out of 70.','Correction recovered four of seven initial failures on the core benchmark. The 12 adversarial questions are a separate set, testing a different contract.','<div class="ledger-controls" role="group" aria-label="Compare core execution counts"><button type="button" data-ledger="before" aria-pressed="false">Before correction · 63</button><button type="button" data-ledger="after" aria-pressed="true">After correction · 67</button></div><p class="ledger-result" aria-live="polite">67 of 70 core queries executed successfully. Four recovered; three still unsuccessful.</p>'),
('meaning','09 / THE EDGE OF THE MAP','h2','It ran.<br><em>Did it answer?</em>','Arriving is not the same as being right.','Execution success does not establish whether the SQL answered the intended business question. That is the next evaluation boundary—and where this atlas stops.','<a class="case-link" href="/work/querypilot/">Read the QueryPilot engineering story <span>↗</span></a><a class="restart" href="#fold">Fold back to the beginning ↑</a><details><summary>Read the source boundary</summary><p>Day 6 evaluation at repository commit 1b75476, recorded 25 February 2026. Only the question, schema names, final SQL, attempt count and published aggregate are represented as evidence. No live inference, query execution or real database topology is shown.</p></details>')]
sections=''.join(f'<section id="{id}" data-study-scene {"data-study-ending" if idx==8 else ""}><div class="narration"><p class="eyebrow">{label}</p><{tag}>{title}</{tag}><p class="lead">{lead}</p><p class="body-copy">{body}</p>{extra}</div></section>' for idx,(id,label,tag,title,lead,body,extra) in enumerate(chapters))
nav=''.join(f'<a href="#{c[0]}" aria-label="Chapter {i+1}: {c[0]}">{i+1:02}</a>' for i,c in enumerate(chapters))
page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>QueryPilot / The Cartographer’s Fold</title><link rel="stylesheet" href="querypilot-world.css"><script type="module" src="querypilot-world.js"></script></head><body data-scene="0"><a class="skip" href="#story">Skip to the story</a><header><a href="/work/querypilot/">QueryPilot <span>↗</span></a><span>FIELD GUIDE Nº 06</span><a href="#meaning">The edge of the map ↓</a></header><figure class="atlas-stage" data-study-stage><div class="coordinate coordinate-top">35° QUESTION / 70 CORE JOURNEYS</div><div class="atlas-camera"><div class="atlas"><img class="atlas-paper" data-study-static src="assets/querypilot-atlas-v1.png" alt="Warm illustrated survey paper with blue coastlines and fold marks.">{svg}<div class="fold fold-west" aria-hidden="true"><span>QUERY<br>PILOT</span><i>AN ATLAS OF<br>BOUNDED CORRECTION</i></div><div class="fold fold-east" aria-hidden="true"><span>Q / P</span><i>UNFOLD<br>TO BEGIN ↗</i></div></div></div><figcaption><span id="map-status">A question waits at the edge.</span><span>EDITORIAL GEOMETRY / COMMITTED RECORD</span></figcaption><div class="coordinate coordinate-bottom">ATLAS / 001—070</div></figure><main id="story">{sections}</main><nav class="chapter-nav" aria-label="Story chapters">{nav}</nav><footer><span>QueryPilot / The Cartographer’s Fold</span><a href="/work/querypilot/">Back to the paper case study ↗</a></footer></body></html>'''
(d/'querypilot-world.html').write_text(page,encoding='utf-8')
