from pathlib import Path
import json,math,html
root=Path(__file__).resolve().parents[1];d=root/'design/directions'
source=json.loads((root.parent/'upi-fraud-engine/evaluation/backtest_results/backtest_results.json').read_text(encoding='utf-8'))
data={'version':1,'commit':'dbc43ad8952c9d84f7c49b59ec80d54e3bbdafbf','daily':source['daily_metrics'],'cumulative':source['cumulative_metrics'],'budget':source['config']['alert_budget']}
(d/'assets/upi-replay-v1.json').write_text(json.dumps(data,indent=2),encoding='utf-8')
waves=''.join(f'<path d="M-200 {y}C130 {y-110} 230 {y+90} 470 {y-20}S820 {y-140} 1300 {y-50}" stroke="{["#28495b","#345669","#446b79"][n%3]}" stroke-width="{1+n%3*.3}" opacity="{.2+n%4*.08}"/>' for n,y in enumerate(range(-100,1200,22)))
ticks=''.join(f'<path d="M{750+232*math.cos(a):.2f} {425+232*math.sin(a):.2f}L{750+(245 if n%5==0 else 238)*math.cos(a):.2f} {425+(245 if n%5==0 else 238)*math.sin(a):.2f}"/>' for n in range(100) for a in [n*math.tau/100])
flow=''.join(f'<g class="current-light" data-current="{n}"><path d="M-18 0H0" stroke="#cfb57b" opacity=".4"/><circle r="2.4" fill="#f8dc9c"/></g>' for n in range(52))
fraud=''
for n in range(701):
    if n<85:
        a=n*2.399963;r=math.sqrt((n+.5)/85)*150;x=750+math.cos(a)*r;y=425+math.sin(a)*r
    else:
        a=n*2.399963;r=265+((n*73)%220);x=750+math.cos(a)*r;y=425+math.sin(a)*r*.78
    fraud+=f'<circle class="fraud-dot {"caught" if n<85 else "missed"}" cx="{x:.2f}" cy="{y:.2f}" r="{3 if n<85 else 2.3}"/>'
svg=f'''<svg class="harbour-art" data-study-static viewBox="0 0 1200 850" role="img" aria-label="An original vector harbour: signals approach a narrow review gate. In the replay view, 85 lights are inside and 616 remain outside."><defs><radialGradient id="water"><stop stop-color="#193747"/><stop offset="1" stop-color="#081925"/></radialGradient><linearGradient id="stone" x2="1" y2="1"><stop stop-color="#758c89"/><stop offset="1" stop-color="#244754"/></linearGradient><radialGradient id="lamp"><stop stop-color="#ffe6a5" stop-opacity=".5"/><stop offset="1" stop-color="#ffe6a5" stop-opacity="0"/></radialGradient></defs><rect width="1200" height="850" fill="url(#water)"/><g class="currents" fill="none">{waves}</g><g class="harbour"><circle cx="750" cy="425" r="207" fill="#122e3b" fill-opacity=".65"/><path d="M547 377A208 208 0 1 1 547 473" fill="none" stroke="#071622" stroke-width="37"/><path d="M547 377A208 208 0 1 1 547 473" fill="none" stroke="url(#stone)" stroke-width="24"/><path d="M547 377A208 208 0 1 1 547 473" fill="none" stroke="#9bb3ad" stroke-width="1.4"/><g stroke="#bdc0a4" stroke-width="1" opacity=".45">{ticks}</g><circle class="tide-ring" cx="750" cy="425" r="178" fill="none" stroke="#ceae70" stroke-width="2" stroke-dasharray="3 12"/><path class="review-gate" d="M548 381V470" stroke="#eac37d" stroke-width="10"/><g class="lighthouse" transform="translate(928,320)"><ellipse cy="17" rx="26" ry="15" fill="#03141d"/><path d="M-20 9L-12-70H12L20 9Q0 27-20 9" fill="#a0b2a9" stroke="#334f5a" stroke-width="2"/><path d="M-12-70L0-96 12-70" fill="#c98f67"/><path d="M-14-73H14V-56H-14Z" fill="#edc984"/><path d="M0-70V-59M-8-70V-59M8-70V-59" stroke="#394e53"/><circle cy="-65" r="65" fill="url(#lamp)"/></g><path class="light-beam" d="M928 255L470 55Q350 170 330 380Z" fill="#efd18b" opacity=".035"/></g><g class="signal-stream">{flow}</g><g class="fraud-field">{fraud}</g><g class="dial-hand" stroke="#edc581" stroke-width="2"><path d="M750 425L750 181"/><circle cx="750" cy="425" r="7" fill="#edc581"/></g><text x="750" y="418" class="budget-label" text-anchor="middle">0.5%</text><text x="750" y="452" class="budget-sub" text-anchor="middle">PROJECT ALERT BUDGET</text></svg>'''
(d/'assets/upi-harbour-v1.svg').write_text(svg,encoding='utf-8')
days=''.join(f'<button type="button" data-day="{n}" aria-pressed="{"true" if n==0 else "false"}"><small>JUN</small>{n+1:02}</button>' for n in range(7))
rows=''.join(f'<tr><td>{x["date"]}</td><td>{x["num_transactions"]:,}</td><td>{x["num_alerts"]}</td><td>{x["precision"]*100:.2f}%</td><td>{x["recall"]*100:.2f}%</td></tr>' for x in data['daily'])
chapters=[('arrival','01 / THE NARROW HARBOUR','h1','The sea doesn’t stop.<br><em>The queue has to.</em>','UPI Fraud Engine','A story about the signals we can review—and the ones we miss. Scroll to enter the harbour.','<a class="enter" href="#current">Follow the current ↓</a>'),
('current','02 / TIME MOVES ONE WAY','h2','Only the past<br>can guide this light.','Transactions arrive with history, not hindsight.','Temporal and behavioural features use information available before the transaction. The frozen model returns a risk score. These moving lights are an illustration, not a transaction log.',''),
('gate','03 / THE REVIEW GATE','h2','The harbour<br>has a capacity.','A 0.5% alert budget is the project’s operating assumption.','The highest-risk fraction enters review. The opening is a visual metaphor, not a score threshold scale or evidence of a real team’s staffing. A risk score is not a fraud verdict.','<p class="side-note">Budget limits the queue.<br>It does not make the sea safe.</p>'),
('heldout','04 / ONE EVALUATION','h2','A bright signal.<br>A narrow reach.','Held-out evaluation · 85,429 transactions','Precision describes the flagged set. Recall describes the fraud that was caught. At this budget, most fraud is missed. Read both numbers together.','<div class="metric-pair"><div><strong>92.06<small>%</small></strong><span>PRECISION</span></div><div><strong>12.81<small>%</small></strong><span>RECALL</span></div></div><p class="footnote">Production XGBoost evaluation · 22 January 2026</p>'),
('replay','05 / SEVEN DIFFERENT TIDES','h2','Now let<br>the days pass.','A separate replay · 1–7 June 2025','Choose a recorded day. The dial moves through real daily precision, recall and alert counts. It does not simulate an untested threshold.','<div class="day-controls" role="group" aria-label="Inspect a recorded replay day">'+days+'</div><div class="day-record" aria-live="polite"><span id="day-date">1 June 2025</span><div><strong id="day-precision">68.75%</strong><span>PRECISION</span><strong id="day-recall">10.68%</strong><span>RECALL</span></div><p id="day-counts">16 alerts / 3,101 transactions</p></div>'),
('separate','06 / TWO RECORDS, TWO QUESTIONS','h2','The second number<br>gets its own story.','Replay · 22,071 transactions across seven days','The replay recorded 75.22% precision and 12.13% recall. It is not the held-out test. The replay reports zero budget violations under its policy; daily alert counts use whole transactions.','<div class="metric-pair"><div><strong>75.22<small>%</small></strong><span>PRECISION</span></div><div><strong>12.13<small>%</small></strong><span>RECALL</span></div></div>'),
('missed','07 / OUTSIDE THE LIGHT','h2','Keep the darkness<br>in the picture.','85 caught. 616 missed. Of 701 fraudulent transactions.','Each point here represents one fraudulent transaction counted in the replay. Positions are editorial. The 28 false positives are separate: 113 alerts included 85 true positives and 28 false positives.','<div class="reveal-controls" role="group" aria-label="Inspect replay fraud counts"><button type="button" data-view="all" aria-pressed="true">Show the whole picture</button><button type="button" data-view="caught" aria-pressed="false">Focus on the 85 caught</button></div><p class="reveal-result" aria-live="polite">85 caught inside. 616 missed outside. Both remain part of the record.</p>'),
('record','08 / A SIGNAL, NOT A VERDICT','h2','Help someone<br><em>look closer.</em>','Prioritise a review. Leave the verdict to it.','UPI Fraud Engine’s useful contract is a bounded queue with its trade-offs visible. Longer replay and real review feedback remain future work, not claimed operational impact.','<a class="case-link" href="/work/upi-fraud-engine/">Read the engineering story <span>↗</span></a><a class="restart" href="#arrival">Return to the current ↑</a><details><summary>Inspect the seven-day record</summary><div class="table-wrap"><table><caption>Committed replay · dbc43ad</caption><thead><tr><th>Date</th><th>Rows</th><th>Alerts</th><th>Precision</th><th>Recall</th></tr></thead><tbody>'+rows+'</tbody></table></div><p>Held-out and replay records remain separate. No live transaction scoring occurs in this world.</p></details>')]
sections=''.join(f'<section id="{id}" data-study-scene {"data-study-ending" if n==7 else ""}><div class="copy"><p class="eyebrow">{label}</p><{tag}>{title}</{tag}><p class="lead">{lead}</p><p>{body}</p>{extra}</div></section>' for n,(id,label,tag,title,lead,body,extra) in enumerate(chapters))
nav=''.join(f'<a href="#{c[0]}" aria-label="Chapter {i+1}: {c[0]}">{i+1:02}</a>' for i,c in enumerate(chapters))
page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>UPI Fraud Engine / The Narrow Harbour</title><link rel="stylesheet" href="upi-fraud-engine-world.css"><script type="module" src="upi-fraud-engine-world.js"></script></head><body data-scene="0"><a class="skip" href="#story">Skip to the story</a><header><a href="/work/upi-fraud-engine/">UPI Fraud Engine ↗</a><span>THE NARROW HARBOUR</span></header><figure class="sea" data-study-stage>{svg}<figcaption><span id="sea-status">The current continues.</span><span>ILLUSTRATED SIGNALS / RECORDED EVIDENCE</span></figcaption></figure><main id="story">{sections}</main><nav class="chapter-nav" aria-label="Story chapters">{nav}</nav><footer>UPI Fraud Engine / A signal is a reason to review.</footer><script id="upi-record" type="application/json">{json.dumps(data).replace('<', '&lt;')}</script></body></html>'''
(d/'upi-fraud-engine-world.html').write_text(page,encoding='utf-8')
